import Head from "next/head";
import styles from "./Shop.module.css";
import Header from "@/components/Header";
import Footer from "@/components/footer/Footer";
import ProductCard from "@/components/cards/ProductCard";
import { useRouter } from "next/router";
import { Aboreto } from "@next/font/google";
const aboreto = Aboreto({
  subsets: ["latin"],
  weight: ["400"],
  fallback: ["sans-serif"],
});

export default function Home() {
  const router = useRouter();
  const { category } = router.query;
  return (
    <>
      <Head>
        <title>{category}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${aboreto.className}`}>
        <Header />
        <h1 className={styles.pageTitle}>{category}s</h1>
        <div className={styles.productsContainer}>
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
          <ProductCard />
        </div>
        <Footer />
      </main>
    </>
  );
}
