import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import LatestDrops from "@/components/LatestDrops";
import Categories from "@/components/Categories";
import Footer from "@/components/footer/Footer";

import { Aboreto } from "@next/font/google";
const aboreto = Aboreto({
  subsets: ["latin"],
  weight: ["400"],
  fallback: ["sans-serif"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Vajradhara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${aboreto.className}`}>
        <Hero />
        <LatestDrops />
        <Categories />
      </main>
      <Footer />
    </>
  );
}
